### PR TITLE
Add Slice type definition file

### PR DESCRIPTION
**Pull request by datdoan92**

### CODE REVIEW

**Comment by datdoan92** [comment]
Thanks @chiliec

**Comment by chiliec** [comment]
@datdoan92 is it will be in @toncenter or only in your fork?

**Comment by datdoan92** [comment]
@chiliec only my :)

**Comment by chiliec** [comment]
Original repository isn't accept PRs? Or why you decided to support your own fork?

**Comment by datdoan92** [comment]
> Original repository isn't accept PRs? Or why you decided to support your own fork?

Yes. the PR not accepted yet. i need the type to fix my personal project

**Pull request merged**
